In [2]:
import pandas as pd
from numpy import *
import numpy as np
from sklearn import preprocessing
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import neighbors

data =pd.read_csv('dataset.csv')

In [25]:
data[['Personality (Class label)']]

Personality (Class label)
0                 extraverted
1                     serious
2                  dependable
3                 extraverted
4                      lively
..                        ...
704               responsible
705                dependable
706                   serious
707               extraverted
708               extraverted

[709 rows x 1 columns]

In [15]:
array = data.values

for i in range(len(data['Gender'])):
    if data['Gender'][i]=="Male":
        data['Gender'][i]=1
    else:
        data['Gender'][i]=0


<ipython-input-15-547ede50fb07>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Gender'][i]=1
<ipython-input-15-547ede50fb07>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Gender'][i]=0


In [30]:
import sklearn.metrics as metrics

In [31]:
testdata 

Gender  Age  openness  neuroticism  conscientiousness  agreeableness  \
0    Female   20         7            9                  9              5   
1      Male   17         5            4                  5              2   
2    Female   25         5            5                  7              2   
3    Female   18         6            2                  7              4   
4    Female   19         2            4                  7              1   
..      ...  ...       ...          ...                ...            ...   
310  Female   19         6            5                  6              4   
311    Male   18         2            5                  8              3   
312    Male   18         7            5                  6              2   
313    Male   23         6            7                  5              4   
314  Female   18         5            7                  3              5   

     extraversion Personality (class label)  
0               5                dependable  
1               4                   serious  
2               4                   serious  
3               7                   serious  
4               3               responsible  
..            ...                       ...  
310             3               extraverted  
311             7                dependable  
312             7                   serious  
313             3               extraverted  
314             6               extraverted  

[315 rows x 8 columns]

In [34]:
X=data[['Gender','Age','openness','neuroticism','conscientiousness','agreeableness','extraversion']]
y=data[['Personality (Class label)']]
mul_lr = linear_model.LogisticRegression(multi_class='multinomial', solver='newton-cg',max_iter =1000)
mul_lr.fit(X, y)

testdata =pd.read_csv('test.csv')
for i in range(len(testdata['Gender'])):
    if testdata['Gender'][i]=="Male":
        testdata['Gender'][i]=1
    else:
        testdata['Gender'][i]=0
X_test=testdata [['Gender','Age','openness','neuroticism','conscientiousness','agreeableness','extraversion']]
y_test=testdata [['Personality (class label)']]

y_pred=mul_lr.predict(X_test)


accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
<ipython-input-34-64552dd41e9a>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testdata['Gender'][i]=0
<ipython-input-34-64552dd41e9a>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testdata['Gender'][i]=1


0.8571428571428571

In [40]:
from sklearn.ensemble import AdaBoostClassifier
knn = AdaBoostClassifier()
knn.fit(X, y)

y_pred = knn.predict(X_test)

confusion = metrics.confusion_matrix(y_test, y_pred)
print("\n\n\n")
print(confusion)
print(metrics.classification_report(y_test, y_pred))
accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy of model: {}%".format(accuracy*100))





[[ 5  8  0  0  8]
 [11 30 15  4 17]
 [ 2  7  4  3  8]
 [ 3  7  3 10 17]
 [29 33 27  3 61]]
              precision    recall  f1-score   support

  dependable       0.10      0.24      0.14        21
 extraverted       0.35      0.39      0.37        77
      lively       0.08      0.17      0.11        24
 responsible       0.50      0.25      0.33        40
     serious       0.55      0.40      0.46       153

    accuracy                           0.35       315
   macro avg       0.32      0.29      0.28       315
weighted avg       0.43      0.35      0.38       315

Accuracy of model: 34.92063492063492%


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [41]:
from sklearn.ensemble import RandomForestClassifier
knn = RandomForestClassifier()
knn.fit(X, y)

y_pred = knn.predict(X_test)

confusion = metrics.confusion_matrix(y_test, y_pred)
print("\n\n\n")
print(confusion)
print(metrics.classification_report(y_test, y_pred))
accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy of model: {}%".format(accuracy*100))





[[ 6  5  2  1  7]
 [16 30 11  4 16]
 [ 6  3  3  5  7]
 [ 4  6  5 10 15]
 [28 36 20 25 44]]
              precision    recall  f1-score   support

  dependable       0.10      0.29      0.15        21
 extraverted       0.38      0.39      0.38        77
      lively       0.07      0.12      0.09        24
 responsible       0.22      0.25      0.24        40
     serious       0.49      0.29      0.36       153

    accuracy                           0.30       315
   macro avg       0.25      0.27      0.24       315
weighted avg       0.37      0.30      0.32       315

Accuracy of model: 29.523809523809526%


<ipython-input-41-193f3a94013f>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  knn.fit(X, y)
